# Generated by Django 5.0.3 on 2024-03-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('ATM', models.CharField(default='False', max_length=100)),
                ('Branch', models.CharField(default='False', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostCode', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=100)),
                ('Remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GSTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTName', models.CharField(max_length=100)),
                ('SGST', models.IntegerField(default=0)),
                ('IGST', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Mobile1', models.CharField(max_length=11)),
                ('Mobile2', models.CharField(max_length=11)),
                ('Remarks', models.TextField()),
            ],
        ),
    ]
