# Generated by Django 5.0.3 on 2024-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_labourmodel_mobile1_alter_labourmodel_mobile2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=0)),
                ('PartyName', models.CharField(max_length=100)),
                ('Cluster', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('GSTNo', models.CharField(max_length=100)),
                ('NO1', models.CharField(blank=True, max_length=100, null=True)),
                ('NO2', models.CharField(blank=True, max_length=100, null=True)),
                ('NO3', models.CharField(blank=True, max_length=100, null=True)),
                ('NO4', models.CharField(blank=True, max_length=100, null=True)),
                ('NO5', models.CharField(blank=True, max_length=100, null=True)),
                ('NO6', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
