# Generated by Django 5.0.3 on 2024-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeNo', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('HSNCode', models.IntegerField(default=0)),
                ('Unit', models.CharField(max_length=100)),
                ('Rate', models.IntegerField(default=0)),
                ('Remarks', models.TextField()),
                ('GSTName', models.CharField(max_length=100)),
                ('SGST', models.IntegerField(default=0)),
                ('IGSTName', models.CharField(blank=True, max_length=100, null=True)),
                ('IGST', models.IntegerField(default=0)),
            ],
        ),
    ]
