# Generated by Django 5.0.3 on 2024-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ratemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gstmodel',
            old_name='IGST',
            new_name='CGST',
        ),
        migrations.AddField(
            model_name='ratemodel',
            name='CGST',
            field=models.IntegerField(default=0),
        ),
    ]
