# Generated by Django 5.0.3 on 2024-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_igst_gstmodel_cgst_ratemodel_cgst'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField(default=0)),
                ('RCCode', models.CharField(max_length=100)),
                ('RCDescription', models.TextField()),
                ('Quantity', models.CharField(max_length=100)),
                ('Rate', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('Labour', models.IntegerField(default=0)),
            ],
        ),
    ]
