# Generated by Django 5.0 on 2024-04-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_countmodel_rcmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermodel',
            name='HubLocation',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
