# Generated by Django 5.0 on 2024-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_clustermodel_hublocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField(default=0)),
                ('PartyName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=100)),
                ('Cluster', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('NO1', models.CharField(blank=True, max_length=100, null=True)),
                ('NO2', models.CharField(blank=True, max_length=100, null=True)),
                ('NO3', models.CharField(blank=True, max_length=100, null=True)),
                ('NO4', models.CharField(blank=True, max_length=100, null=True)),
                ('CallType', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('CloseDate', models.DateField()),
                ('CodeNo', models.CharField(max_length=100)),
                ('CostCode', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('CCName', models.CharField(blank=True, max_length=100, null=True)),
                ('Problem', models.TextField()),
                ('ChallanNo', models.CharField(max_length=100)),
                ('ChallanDate', models.DateField()),
                ('CallAllocatedTo', models.CharField(blank=True, max_length=100, null=True)),
                ('EstimateRecd', models.CharField(blank=True, max_length=100, null=True)),
                ('WorkEngaged', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.TextField()),
                ('TotalAmount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
