# Generated by Django 5.0.3 on 2024-06-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_entrymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='complet',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
