# Generated by Django 5.0.3 on 2024-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_entrymodel_complet'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceData', models.DateField(blank=True, null=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=100, null=True)),
                ('BillMonth', models.CharField(blank=True, max_length=100, null=True)),
                ('BillYear', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(blank=True, max_length=100, null=True)),
                ('datein', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('FromDate', models.DateField(blank=True, null=True)),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTAmount', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalAmount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='countmodel',
            name='Invoice',
            field=models.IntegerField(default=0),
        ),
    ]
