# Generated by Django 5.0.3 on 2024-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_invoicemodel_countmodel_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField(blank=True, default=0, null=True)),
                ('RCCode', models.CharField(blank=True, max_length=100, null=True)),
                ('RCDescription', models.TextField(blank=True, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Rate', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('Labour', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('Amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('GSTRate', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTAmount', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTTA', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('TotalAmount', models.CharField(blank=True, default='0', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='Amount',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='Counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='Labour',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='RCCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='RCDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rcmodel',
            name='Rate',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
