# Generated by Django 5.0.3 on 2024-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_invoicercmodel_alter_rcmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicercmodel',
            name='InvoiceNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
