# Generated by Django 5.0.3 on 2024-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_invoicercmodel_invoiceno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='countmodel',
            name='Invoice',
        ),
    ]
