# Generated by Django 5.0.3 on 2024-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_icountmodel_remove_countmodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='PartyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
