# Generated by Django 5.0.3 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_qcountmodel_qttmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField(default=0)),
                ('Date', models.DateField()),
                ('PartyName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Problem', models.TextField()),
                ('Code', models.CharField(max_length=100)),
                ('CallRef', models.CharField(max_length=100)),
                ('CallNo', models.CharField(max_length=100)),
                ('WorkEngaged', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('AreaOfWork', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.TextField()),
                ('TC', models.TextField()),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTAmount', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalAmount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoicercmodel',
            name='HSNCode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoicercmodel',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qttmodel',
            name='HSNCode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='qttmodel',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='HSNCode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
