# Generated by Django 5.0.3 on 2024-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_entrymodel_calldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymodel',
            name='Active',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
