# Generated by Django 5.0.3 on 2024-07-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_entrymodel_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='qttmodel',
            name='TYPES',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
